### ISSUE TITLE
MAWB-18: [400] Bad Request

### ISSUE THREAD

**Issue by Orbit419** [boroda4436/mate_academy_wikibot_NOV18#65]
Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity

**Comment by Orbit419** [comment]
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 38
	at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:169)
	at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:23)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:717)
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:47)
	at mate.academy.wikibot.bot.Bot.sendMsg(Bot.java:92)
	at mate.academy.wikibot.bot.Bot.onUpdateReceived(Bot.java:67)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:305)

Were entered: Java, q, qw
Without exception: stopgame

**Comment by boroda4436** [comment]
@Orbit419 please see here how to describe the bug correctly:
https://reqtest.com/testing-blog/why-testers-need-to-be-highly-skillful-at-describing-bugs/

please edit your description and add the following items:
1) Summary
2) Steps To Reproduce
3) Expected results
4) Actual results

**Comment by romaanankin** [comment]
could be a possible decision [link](https://github.com/irazasyed/telegram-bot-sdk/issues/493)

**Comment by Orbit419** [comment]
Fixed
